<script setup>
import { computed, ref } from 'vue'
import { useAuthStore } from '@/identity-access/application/stores/auth.store'
import { useSafeLabDemoStore } from '@/shared/application/stores/demo.store'
const auth = useAuthStore(); const demo = useSafeLabDemoStore(); auth.restoreSession()
const search = ref(''); const severity = ref('all'); const status = ref('all'); const selectedAlert = ref(null)
const user = computed(() => auth.currentUser)
const alerts = computed(() => demo.scopedItems('alerts', user.value).filter((alert) => {
  const text = `${alert.title} ${alert.message} ${alert.type} ${alert.assignedTo}`.toLowerCase()
  return text.includes(search.value.toLowerCase()) && (severity.value === 'all' || alert.severity === severity.value) && (status.value === 'all' || alert.status === status.value)
}))
const summary = computed(() => ({
  critical: alerts.value.filter((a)=>a.severity==='critical' && a.status !== 'resolved').length,
  unack: alerts.value.filter((a)=>a.status==='active').length,
  total: alerts.value.length,
  resolved: alerts.value.filter((a)=>a.status==='resolved').length
}))
function open(alert){ selectedAlert.value = alert }
function ack(){ demo.acknowledgeAlert(selectedAlert.value.id); selectedAlert.value = demo.alerts.find(a=>a.id===selectedAlert.value.id) }
function resolve(){ demo.resolveAlert(selectedAlert.value.id); selectedAlert.value = demo.alerts.find(a=>a.id===selectedAlert.value.id) }
function escalate(){ demo.escalateAlert(selectedAlert.value.id); selectedAlert.value = demo.alerts.find(a=>a.id===selectedAlert.value.id) }
</script>
<template>
  <section class="page">
    <div class="page-hero compact"><div><p class="eyebrow">Monitoring & operations</p><h1>Alerts center</h1><p>Filter, review, acknowledge, resolve or escalate operational alerts generated by sensors, compliance rules and remote actions.</p></div></div>
    <div class="kpi-grid"><article class="kpi-card danger"><span class="kpi-icon"><i class="pi pi-exclamation-triangle"></i></span><div class="kpi-copy"><span>Critical alerts</span><strong>{{ summary.critical }}</strong><small>Immediate action</small></div></article><article class="kpi-card warning"><span class="kpi-icon"><i class="pi pi-bell"></i></span><div class="kpi-copy"><span>Unacknowledged</span><strong>{{ summary.unack }}</strong><small>Pending review</small></div></article><article class="kpi-card"><span class="kpi-icon"><i class="pi pi-list"></i></span><div class="kpi-copy"><span>Total alerts</span><strong>{{ summary.total }}</strong><small>Filtered events</small></div></article><article class="kpi-card success"><span class="kpi-icon"><i class="pi pi-check"></i></span><div class="kpi-copy"><span>Resolved</span><strong>{{ summary.resolved }}</strong><small>Closed events</small></div></article></div>
    <div class="filter-bar"><div class="field"><label>Search</label><input v-model="search" class="input" placeholder="Device, location, type..."></div><div class="field"><label>Severity</label><select v-model="severity" class="select"><option value="all">All severities</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option></select></div><div class="field"><label>Status</label><select v-model="status" class="select"><option value="all">All statuses</option><option value="active">Active</option><option value="acknowledged">Acknowledged</option><option value="escalated">Escalated</option><option value="resolved">Resolved</option></select></div><div class="actions"><button class="btn" @click="search='';severity='all';status='all'">Clear filters</button></div></div>
    <article class="card table-card"><table class="responsive-table"><thead><tr><th>Alert</th><th>Scope</th><th>Severity</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody><tr v-for="alert in alerts" :key="alert.id"><td data-label="Alert"><strong>{{ alert.title }}</strong><br><small>{{ alert.message }}</small></td><td data-label="Scope">{{ alert.assignedTo }}<br><small>{{ alert.type }}</small></td><td data-label="Severity"><span :class="['status-pill', alert.severity]">{{ alert.severity }}</span></td><td data-label="Status"><span :class="['status-pill', alert.status]">{{ alert.status }}</span></td><td data-label="Created">{{ new Date(alert.createdAt).toLocaleString() }}</td><td data-label="Actions"><button class="btn small primary" @click="open(alert)">Details</button></td></tr></tbody></table></article>
    <div v-if="selectedAlert" class="modal-backdrop" @click.self="selectedAlert=null"><article class="modal-card medium"><header class="modal-header"><div><p class="eyebrow">Alert detail</p><h2>{{ selectedAlert.title }}</h2><p>{{ selectedAlert.message }}</p></div><button class="icon-action" @click="selectedAlert=null"><i class="pi pi-times"></i></button></header><div class="pair-grid"><div class="pair-box"><span>Type</span><strong>{{ selectedAlert.type }}</strong></div><div class="pair-box"><span>Assigned to</span><strong>{{ selectedAlert.assignedTo }}</strong></div><div class="pair-box"><span>Severity</span><strong>{{ selectedAlert.severity }}</strong></div><div class="pair-box"><span>Status</span><strong>{{ selectedAlert.status }}</strong></div></div><footer class="modal-footer"><button class="btn" @click="ack">Acknowledge</button><button class="btn success" @click="resolve">Resolve</button><button class="btn danger" @click="escalate">Escalate</button></footer></article></div>
  </section>
</template>
