<script setup>
import { useSafeLabDemoStore } from '@/shared/application/stores/demo.store'
const demo = useSafeLabDemoStore()
</script>
<template><section class="page"><div class="page-hero compact"><div><p class="eyebrow">Notifications</p><h1>Notification history</h1><p>Messages generated by alerts, incidents, remote commands, assets and reports.</p></div><button class="btn" @click="demo.markAllNotificationsRead()">Mark all read</button></div><article class="card"><div class="item-list"><article v-for="n in demo.notifications" :key="n.id" class="list-row compact"><span><strong>{{ n.title }}</strong><small>{{ n.message }} · {{ new Date(n.createdAt).toLocaleString() }}</small></span><span :class="['status-pill', n.severity]">{{ n.severity }}</span><span :class="['status-pill', n.unread ? 'warning' : 'success']">{{ n.unread ? 'unread' : 'read' }}</span></article></div></article></section></template>
