<script setup>
import { computed, ref } from 'vue'
import { useAuthStore } from '@/identity-access/application/stores/auth.store'
import { useSafeLabDemoStore } from '@/shared/application/stores/demo.store'
const auth = useAuthStore(); const demo = useSafeLabDemoStore(); auth.restoreSession()
const search = ref(''); const severity = ref('all'); const status = ref('all')
const user = computed(() => auth.currentUser)
const logs = computed(() => demo.auditLogs.filter((log) => {
  const text = `${log.actor} ${log.action} ${log.module} ${log.evidence}`.toLowerCase()
  return text.includes(search.value.toLowerCase()) && (severity.value === 'all' || log.severity === severity.value) && (status.value === 'all' || log.status === status.value)
}))
const summary = computed(() => ({ total: demo.auditLogs.length, reviewed: demo.auditLogs.filter(l=>l.status==='reviewed').length, pending: demo.auditLogs.filter(l=>l.status==='pending').length, critical: demo.auditLogs.filter(l=>l.severity==='critical').length, integrity: Math.round((demo.auditLogs.filter(l=>l.evidence).length / Math.max(1, demo.auditLogs.length))*100) }))
</script>
<template>
  <section class="page">
    <div class="page-hero compact"><div><p class="eyebrow">Audit & traceability</p><h1>Audit trail</h1><p>Every simulated action across SafeLab creates traceability: sensors, alerts, incidents, assets, reports and remote commands.</p></div><div class="hero-score"><span>Integrity score</span><strong>{{ summary.integrity }}%</strong><small>Protected records</small></div></div>
    <div class="kpi-grid"><article class="kpi-card"><span class="kpi-icon"><i class="pi pi-list"></i></span><div class="kpi-copy"><span>Total audit logs</span><strong>{{ summary.total }}</strong><small>Days retained</small></div></article><article class="kpi-card success"><span class="kpi-icon"><i class="pi pi-check-circle"></i></span><div class="kpi-copy"><span>Reviewed logs</span><strong>{{ summary.reviewed }}</strong><small>Evidence linked</small></div></article><article class="kpi-card warning"><span class="kpi-icon"><i class="pi pi-clock"></i></span><div class="kpi-copy"><span>Pending review</span><strong>{{ summary.pending }}</strong><small>Requires validation</small></div></article><article class="kpi-card danger"><span class="kpi-icon"><i class="pi pi-shield"></i></span><div class="kpi-copy"><span>Critical events</span><strong>{{ summary.critical }}</strong><small>High priority</small></div></article></div>
    <div class="grid-2"><article class="card table-card"><div class="card-header"><div><p class="eyebrow">Audit control</p><h2>Recent audit records</h2></div></div><div class="filter-bar" style="box-shadow:none;border-radius:18px;margin-bottom:14px"><div class="field"><label>Search</label><input v-model="search" class="input" placeholder="Actor, module, action..."></div><div class="field"><label>Severity</label><select v-model="severity" class="select"><option value="all">All</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option></select></div><div class="field"><label>Status</label><select v-model="status" class="select"><option value="all">All</option><option value="reviewed">Reviewed</option><option value="pending">Pending</option></select></div></div><table class="responsive-table"><thead><tr><th>ID</th><th>Actor</th><th>Action</th><th>Module</th><th>Severity</th><th>Status</th><th>Evidence</th></tr></thead><tbody><tr v-for="log in logs" :key="log.id"><td data-label="ID">{{ log.id }}</td><td data-label="Actor">{{ log.actor }}</td><td data-label="Action">{{ log.action }}</td><td data-label="Module">{{ log.module }}</td><td data-label="Severity"><span :class="['status-pill', log.severity]">{{ log.severity }}</span></td><td data-label="Status"><span :class="['status-pill', log.status]">{{ log.status }}</span></td><td data-label="Evidence">{{ log.evidence }}</td></tr></tbody></table></article><div class="page"><article class="card"><p class="eyebrow">Traceability timeline</p><h2>Latest tracked events</h2><div class="item-list"><div v-for="log in demo.auditLogs.slice(0,5)" :key="log.id" class="list-row"><span><strong>{{ log.action }}</strong><small>{{ log.module }} · {{ new Date(log.createdAt).toLocaleTimeString() }}</small></span><span :class="['status-pill', log.status]">{{ log.status }}</span></div></div></article><article class="card"><p class="eyebrow">Coverage</p><h2>Traceability health</h2><div class="pair-grid"><div class="pair-box"><span>Audit coverage</span><strong>{{ summary.integrity }}%</strong></div><div class="pair-box"><span>Command records</span><strong>{{ demo.remoteCommands.length }}</strong></div><div class="pair-box"><span>Reports</span><strong>{{ demo.reports.length }}</strong></div><div class="pair-box"><span>Evidence ready</span><strong>{{ demo.incidents.reduce((s,i)=>s+i.evidence,0) }}</strong></div></div></article></div></div>
  </section>
</template>
