<script setup>
import { computed, reactive, ref } from 'vue'
import { useAuthStore } from '@/identity-access/application/stores/auth.store'
import { useSafeLabDemoStore } from '@/shared/application/stores/demo.store'
const auth = useAuthStore(); const demo = useSafeLabDemoStore(); auth.restoreSession()
const search = ref(''); const typeFilter = ref('all'); const statusFilter = ref('all'); const modalOpen = ref(false)
const form = reactive({})
const user = computed(() => auth.currentUser)
const facilities = computed(() => demo.scopedFacilities(user.value))
const sensors = computed(() => demo.scopedItems('sensors', user.value).filter((sensor) => {
  const text = `${sensor.name} ${sensor.code} ${sensor.type} ${sensor.responsible}`.toLowerCase()
  return text.includes(search.value.toLowerCase()) && (typeFilter.value === 'all' || sensor.type === typeFilter.value) && (statusFilter.value === 'all' || sensor.status === statusFilter.value)
}))
const summary = computed(() => ({ total: sensors.value.length, normal: sensors.value.filter((s) => s.status === 'normal').length, out: sensors.value.filter((s) => s.status === 'out-of-range').length, invalid: sensors.value.filter((s) => s.status === 'invalid' || s.connection !== 'online').length }))
function valueLabel(sensor){ return `${sensor.value}${sensor.unit || ''}` }
function resetForm() { Object.assign(form, { name: '', code: `SEN-${Date.now().toString().slice(-4)}`, type: 'temperature', unit: '°C', value: 4, min: 2, max: 8, facilityId: facilities.value[0]?.id || 'fac-central', responsible: user.value?.fullName || 'Operator' }) }
function openNew(){ resetForm(); modalOpen.value = true }
function save(){ demo.addSensor({ ...form, status: 'normal', connection: 'online' }); modalOpen.value = false }
</script>
<template>
  <section class="page">
    <div class="page-hero compact"><div><p class="eyebrow">Monitoring</p><h1>Real-time monitoring</h1><p>Monitor registered telemetry, add sensors, calibrate readings and let threshold rules create alerts automatically.</p></div><button class="btn primary" @click="openNew"><i class="pi pi-plus"></i> Add sensor</button></div>
    <div class="kpi-grid"><article class="kpi-card"><span class="kpi-icon"><i class="pi pi-wifi"></i></span><div class="kpi-copy"><span>Total sensors</span><strong>{{ summary.total }}</strong><small>Devices registered</small></div></article><article class="kpi-card success"><span class="kpi-icon"><i class="pi pi-check-circle"></i></span><div class="kpi-copy"><span>Normal readings</span><strong>{{ summary.normal }}</strong><small>Within range</small></div></article><article class="kpi-card danger"><span class="kpi-icon"><i class="pi pi-exclamation-triangle"></i></span><div class="kpi-copy"><span>Out of range</span><strong>{{ summary.out }}</strong><small>Requires review</small></div></article><article class="kpi-card warning"><span class="kpi-icon"><i class="pi pi-times-circle"></i></span><div class="kpi-copy"><span>Invalid</span><strong>{{ summary.invalid }}</strong><small>Disconnected or invalid</small></div></article></div>
    <div class="filter-bar"><div class="field"><label>Search</label><input v-model="search" class="input" placeholder="Sensor, code or responsible"></div><div class="field"><label>Type</label><select v-model="typeFilter" class="select"><option value="all">All types</option><option value="temperature">Temperature</option><option value="humidity">Humidity</option><option value="door">Door</option><option value="vibration">Vibration</option></select></div><div class="field"><label>Status</label><select v-model="statusFilter" class="select"><option value="all">All statuses</option><option value="normal">Normal</option><option value="out-of-range">Out of range</option><option value="invalid">Invalid</option></select></div><div class="actions"><button class="btn" type="button" @click="search=''; typeFilter='all'; statusFilter='all'">Clear filters</button></div></div>
    <div class="sensor-grid"><article v-for="sensor in sensors" :key="sensor.id" :class="['sensor-card', sensor.status !== 'normal' ? 'is-problem' : '']"><div class="card-header"><div><h3>{{ sensor.name }}</h3><p>{{ sensor.code }}</p></div><span :class="['status-pill', sensor.status]">{{ sensor.status }}</span></div><div class="sensor-value"><span class="text-muted">Current {{ sensor.type }}</span><strong>{{ valueLabel(sensor) }}</strong></div><div class="pair-grid"><div class="pair-box"><span>Target</span><strong>{{ sensor.min }} - {{ sensor.max }}{{ sensor.unit }}</strong></div><div class="pair-box"><span>Connection</span><strong>{{ sensor.connection }}</strong></div><div class="pair-box"><span>Responsible</span><strong>{{ sensor.responsible }}</strong></div><div class="pair-box"><span>Last reading</span><strong>{{ new Date(sensor.lastReading).toLocaleTimeString() }}</strong></div></div><div class="actions"><button class="btn small" @click="demo.updateSensor(sensor.id,{ value: sensor.type === 'temperature' ? Number(sensor.value)+1 : sensor.value })">+ reading</button><button class="btn small" @click="demo.updateSensor(sensor.id,{ value: sensor.type === 'temperature' ? 4 : sensor.type === 'humidity' ? 45 : sensor.value, status:'normal' })">Calibrate</button><button class="btn small danger" @click="demo.deleteSensor(sensor.id)">Remove</button></div></article></div>
    <div v-if="modalOpen" class="modal-backdrop" @click.self="modalOpen=false"><article class="modal-card medium"><header class="modal-header"><div><p class="eyebrow">Sensor device</p><h2>Register sensor</h2></div><button class="icon-action" @click="modalOpen=false"><i class="pi pi-times"></i></button></header><form class="modal-form" @submit.prevent="save"><div class="field"><label>Name</label><input v-model="form.name" required class="input"></div><div class="field"><label>Code</label><input v-model="form.code" required class="input"></div><div class="field"><label>Type</label><select v-model="form.type" class="select"><option value="temperature">Temperature</option><option value="humidity">Humidity</option><option value="door">Door</option><option value="vibration">Vibration</option></select></div><div class="field"><label>Facility</label><select v-model="form.facilityId" class="select"><option v-for="facility in facilities" :key="facility.id" :value="facility.id">{{ facility.name }}</option></select></div><div class="field"><label>Current value</label><input v-model="form.value" class="input"></div><div class="field"><label>Unit</label><input v-model="form.unit" class="input"></div><div class="field"><label>Min</label><input v-model="form.min" class="input"></div><div class="field"><label>Max</label><input v-model="form.max" class="input"></div><footer class="modal-footer full"><button class="btn" type="button" @click="modalOpen=false">Cancel</button><button class="btn success" type="submit">Save</button></footer></form></article></div>
  </section>
</template>
