<script setup>
import { computed, ref } from 'vue'
import { useAuthStore } from '@/identity-access/application/stores/auth.store'
import { useSafeLabDemoStore } from '@/shared/application/stores/demo.store'
const auth = useAuthStore(); const demo = useSafeLabDemoStore(); auth.restoreSession()
const typeFilter = ref('all')
const user = computed(() => auth.currentUser)
const actuators = computed(() => demo.scopedItems('actuators', user.value).filter((a) => typeFilter.value === 'all' || a.type === typeFilter.value))
const summary = computed(() => ({ total: actuators.value.length, available: actuators.value.filter(a=>a.status==='online' && a.safetyState==='enabled').length, blocked: actuators.value.filter(a=>a.status!=='online' || a.safetyState==='blocked').length, executed: demo.remoteCommands.length }))
function command(actuator, action){ demo.executeCommand(actuator.id, action, user.value?.fullName || 'Current user') }
</script>
<template>
  <section class="page">
    <div class="page-hero compact"><div><p class="eyebrow">Remote control & actuation</p><h1>Remote control panel</h1><p>Execute safe simulated commands and persist command history, notifications and audit logs.</p></div></div>
    <div class="kpi-grid"><article class="kpi-card"><span class="kpi-icon"><i class="pi pi-sliders-h"></i></span><div class="kpi-copy"><span>Total devices</span><strong>{{ summary.total }}</strong><small>Registered actuators</small></div></article><article class="kpi-card success"><span class="kpi-icon"><i class="pi pi-check"></i></span><div class="kpi-copy"><span>Available</span><strong>{{ summary.available }}</strong><small>Ready for commands</small></div></article><article class="kpi-card warning"><span class="kpi-icon"><i class="pi pi-lock"></i></span><div class="kpi-copy"><span>Blocked</span><strong>{{ summary.blocked }}</strong><small>Locked or offline</small></div></article><article class="kpi-card"><span class="kpi-icon"><i class="pi pi-history"></i></span><div class="kpi-copy"><span>Executed</span><strong>{{ summary.executed }}</strong><small>Remote commands</small></div></article></div>
    <div class="filter-bar"><div class="field"><label>Device type</label><select v-model="typeFilter" class="select"><option value="all">All types</option><option>Relay</option><option>Cooling</option><option>Power cycle</option><option>Lock</option></select></div><div class="actions"><button class="btn" @click="typeFilter='all'">Clear</button></div></div>
    <div class="actuator-grid"><article v-for="actuator in actuators" :key="actuator.id" class="actuator-card"><div class="card-header"><div><h3>{{ actuator.name }}</h3><p>{{ actuator.code }}</p></div><span :class="['status-pill', actuator.status]">{{ actuator.status }}</span></div><div class="pair-grid"><div class="pair-box"><span>Type</span><strong>{{ actuator.type }}</strong></div><div class="pair-box"><span>Safety</span><strong>{{ actuator.safetyState }}</strong></div><div class="pair-box"><span>Linked sensor</span><strong>{{ actuator.linkedSensorId }}</strong></div><div class="pair-box"><span>State</span><strong>{{ actuator.running ? 'Running' : actuator.lastCommand }}</strong></div></div><div v-if="demo.commandInProgress === actuator.id" class="progress"><i style="width: 55%"></i></div><div class="actions"><button class="btn small primary" :disabled="demo.commandInProgress===actuator.id" @click="command(actuator,'Start')">Start</button><button class="btn small" @click="command(actuator,'Stop')">Stop</button><button class="btn small warning" @click="command(actuator,'Reset')">Reset</button></div></article></div>
    <div class="grid-2"><article class="card table-card"><div class="card-header"><div><p class="eyebrow">Command history</p><h2>Latest executions</h2></div></div><table class="responsive-table"><thead><tr><th>Command</th><th>Device</th><th>Status</th><th>Requested by</th><th>Created</th></tr></thead><tbody><tr v-for="cmd in demo.remoteCommands.slice(0,6)" :key="cmd.id"><td data-label="Command">{{ cmd.command }}</td><td data-label="Device">{{ cmd.device }}</td><td data-label="Status"><span :class="['status-pill', cmd.status]">{{ cmd.status }}</span></td><td data-label="Requested by">{{ cmd.requestedBy }}</td><td data-label="Created">{{ new Date(cmd.createdAt).toLocaleString() }}</td></tr></tbody></table></article><article class="card"><div class="card-header"><div><p class="eyebrow">Safety policies</p><h2>Execution guardrails</h2></div></div><div class="item-list"><div class="list-row"><span><strong>Safe command confirmation</strong><small>Every command is validated and audited.</small></span><span class="status-pill success">Active</span></div><div class="list-row"><span><strong>Blocked devices cannot be controlled</strong><small>Locked or offline devices reject commands.</small></span><span class="status-pill success">Active</span></div></div></article></div>
  </section>
</template>
