<script setup>
import { computed, ref } from 'vue'
import { useAuthStore } from '@/identity-access/application/stores/auth.store'
import { useSafeLabDemoStore } from '@/shared/application/stores/demo.store'
const auth = useAuthStore(); const demo = useSafeLabDemoStore(); auth.restoreSession()
const search = ref('')
const user = computed(() => auth.currentUser)
const sensors = computed(() => demo.scopedItems('sensors', user.value))
const incidents = computed(() => demo.scopedItems('incidents', user.value))
const rules = computed(() => demo.complianceRules.filter((rule) => rule.title.toLowerCase().includes(search.value.toLowerCase())))
const violations = computed(() => sensors.value.filter((sensor) => sensor.status !== 'normal'))
const compliantRules = computed(() => rules.value.filter((rule) => !violations.value.some((sensor) => sensor.type === rule.type)).length)
const complianceScore = computed(() => rules.value.length ? Math.round((compliantRules.value / rules.value.length) * 100) : 100)
</script>
<template>
  <section class="page">
    <div class="page-hero compact"><div><p class="eyebrow">Environmental compliance</p><h1>Compliance control</h1><p>Rules react to sensor telemetry and unresolved incidents. Attach evidence and pause rules when needed.</p></div><div class="hero-score"><span>Compliance</span><strong>{{ complianceScore }}%</strong><small>{{ violations.length }} active violations</small></div></div>
    <div class="kpi-grid"><article class="kpi-card"><span class="kpi-icon"><i class="pi pi-check-circle"></i></span><div class="kpi-copy"><span>General compliance</span><strong>{{ complianceScore }}%</strong><small>Current readiness</small></div></article><article class="kpi-card"><span class="kpi-icon"><i class="pi pi-wifi"></i></span><div class="kpi-copy"><span>Monitored sensors</span><strong>{{ sensors.length }}</strong><small>Telemetry inputs</small></div></article><article class="kpi-card danger"><span class="kpi-icon"><i class="pi pi-exclamation-triangle"></i></span><div class="kpi-copy"><span>Violations</span><strong>{{ violations.length }}</strong><small>Out of policy</small></div></article><article class="kpi-card warning"><span class="kpi-icon"><i class="pi pi-file"></i></span><div class="kpi-copy"><span>Pending evidence</span><strong>{{ incidents.filter(i=>!i.evidence).length }}</strong><small>Need attachment</small></div></article></div>
    <div class="filter-bar"><div class="field"><label>Search rules</label><input v-model="search" class="input" placeholder="Temperature, humidity, evidence..."></div><div class="actions"><button class="btn primary" @click="demo.generateReport('Compliance','Compliance evidence report')">Generate compliance report</button><button class="btn" @click="search=''">Clear search</button></div></div>
    <div class="grid-2"><article class="card"><div class="card-header"><div><p class="eyebrow">Active rules</p><h2>Rules and affected sensors</h2></div></div><div class="item-list"><article v-for="rule in rules" :key="rule.id" class="list-row compact"><span><strong>{{ rule.title }}</strong><small>Type: {{ rule.type }} · Evidence: {{ rule.requiredEvidence ? 'required' : 'optional' }}</small></span><span :class="['status-pill', violations.some(s=>s.type===rule.type) ? 'danger' : 'success']">{{ violations.some(s=>s.type===rule.type) ? 'Violation' : 'Complies' }}</span><button class="btn small" @click="demo.toggleRule(rule.id)">{{ rule.status === 'active' ? 'Pause' : 'Activate' }}</button></article></div></article><article class="card"><div class="card-header"><div><p class="eyebrow">Violation evidence</p><h2>Current deviations</h2></div></div><div class="item-list"><article v-for="sensor in violations" :key="sensor.id" class="list-row compact"><span><strong>{{ sensor.name }}</strong><small>Value: {{ sensor.value }}{{ sensor.unit }} · Range: {{ sensor.min }} - {{ sensor.max }}{{ sensor.unit }}</small></span><span :class="['status-pill', sensor.status]">{{ sensor.status }}</span><button class="btn small success" @click="demo.updateSensor(sensor.id,{ value: sensor.type==='temperature'?4:sensor.type==='humidity'?45:sensor.type==='vibration'?1:sensor.value, status:'normal' })">Validate</button></article></div></article></div>
    <article class="card"><div class="card-header"><div><p class="eyebrow">Evidence workflow</p><h2>Incidents requiring compliance evidence</h2></div></div><div class="item-list"><article v-for="incident in incidents" :key="incident.id" class="list-row compact"><span><strong>{{ incident.code }} · {{ incident.title }}</strong><small>Evidence: {{ incident.evidence }} · {{ incident.description }}</small></span><span :class="['status-pill', incident.status]">{{ incident.status }}</span><button class="btn small primary" @click="demo.attachEvidence(incident.id)">Attach evidence</button></article></div></article>
  </section>
</template>
