<script setup>
import { computed, ref } from 'vue'
import { useAuthStore } from '@/identity-access/application/stores/auth.store'
import { useSafeLabDemoStore } from '@/shared/application/stores/demo.store'
const auth = useAuthStore(); const demo = useSafeLabDemoStore(); auth.restoreSession()
const type = ref('Operational')
const user = computed(() => auth.currentUser)
const summary = computed(() => demo.dashboardSummary(user.value))
const reports = computed(() => demo.reports.slice(0, 6))
const alerts = computed(() => demo.scopedItems('alerts', user.value).slice(0, 5))
function generate(){ demo.generateReport(type.value, `${type.value} analytics ${new Date().toLocaleDateString()}`) }
</script>
<template>
  <section class="page">
    <div class="page-hero compact"><div><p class="eyebrow">Reports & analytics</p><h1>Analytics overview</h1><p>Generate reports from operational, compliance, incident and audit information.</p></div><div class="actions"><select v-model="type" class="select"><option>Operational</option><option>Compliance</option><option>Audit</option><option>Incident</option></select><button class="btn primary" @click="generate">Generate report</button></div></div>
    <div class="kpi-grid"><article class="kpi-card"><span class="kpi-icon"><i class="pi pi-file"></i></span><div class="kpi-copy"><span>Reports</span><strong>{{ demo.reports.length }}</strong><small>Generated exports</small></div></article><article class="kpi-card warning"><span class="kpi-icon"><i class="pi pi-bell"></i></span><div class="kpi-copy"><span>Active alerts</span><strong>{{ summary.activeAlerts }}</strong><small>Operational review</small></div></article><article class="kpi-card"><span class="kpi-icon"><i class="pi pi-chart-line"></i></span><div class="kpi-copy"><span>Telemetry</span><strong>{{ summary.telemetryScore }}%</strong><small>Coverage score</small></div></article><article class="kpi-card danger"><span class="kpi-icon"><i class="pi pi-exclamation-triangle"></i></span><div class="kpi-copy"><span>Risk load</span><strong>{{ summary.openIncidents + summary.activeAlerts }}</strong><small>Needs attention</small></div></article></div>
    <div class="grid-2"><article class="card"><div class="card-header"><div><p class="eyebrow">Monitoring trends</p><h2>Operational indicators</h2></div></div><div class="item-list"><div class="list-row"><span><strong>Health score</strong><small>Current dashboard health</small></span><strong>{{ summary.healthScore }}%</strong></div><div class="list-row"><span><strong>Compliance score</strong><small>Current rule readiness</small></span><strong>{{ summary.complianceScore }}%</strong></div><div class="list-row"><span><strong>Open alerts</strong><small>Alerts still requiring review</small></span><strong>{{ summary.activeAlerts }}</strong></div></div></article><article class="card"><div class="card-header"><div><p class="eyebrow">Operational risk</p><h2>Risk snapshot</h2></div><span :class="['status-pill', summary.healthScore > 70 ? 'success' : 'danger']">{{ summary.healthScore > 70 ? 'Controlled' : 'High risk' }}</span></div><div class="pair-grid"><div class="pair-box"><span>Critical alerts</span><strong>{{ summary.criticalAlerts }}</strong></div><div class="pair-box"><span>Out-of-range sensors</span><strong>{{ summary.abnormalSensors }}</strong></div><div class="pair-box"><span>Disconnected sensors</span><strong>{{ summary.disconnectedSensors }}</strong></div><div class="pair-box"><span>Compliance</span><strong>{{ summary.complianceScore }}%</strong></div></div></article></div>
    <div class="grid-2"><article class="card"><div class="card-header"><div><p class="eyebrow">Recent reports</p><h2>Generated files</h2></div></div><div class="item-list"><article v-for="report in reports" :key="report.id" class="list-row compact"><span><strong>{{ report.title }}</strong><small>{{ report.type }} · {{ new Date(report.generatedAt).toLocaleString() }}</small></span><span class="status-pill success">{{ report.format }}</span><button class="btn small">Download</button></article></div></article><article class="card"><div class="card-header"><div><p class="eyebrow">Recent alerts</p><h2>Inputs for analytics</h2></div></div><div class="item-list"><article v-for="alert in alerts" :key="alert.id" class="list-row compact"><span><strong>{{ alert.title }}</strong><small>{{ alert.message }}</small></span><span :class="['status-pill', alert.severity]">{{ alert.severity }}</span></article></div></article></div>
  </section>
</template>
